#!/bin/bash

# Enable Canonical partner repositories
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

# Install Ubuntu Restricted Extras for media codecs
sudo apt-get install ubuntu-restricted-extras

# Install VLC media player
sudo apt-get install vlc

# Install tlp - improve battery life and reduce overheating
sudo add-apt-repository ppa:linrunner/tlp
sudo apt-get update
sudo apt-get install tlp tlp-rdw
sudo tlp start
