#!/bin/bash

# Enable Canonical partner repositories
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

# Install Ubuntu Restricted Extras for media codecs
sudo apt-get install ubuntu-restricted-extras

# Install VLC media player
sudo apt-get install vlc

# Install tlp - improve battery life and reduce overheating
sudo add-apt-repository ppa:linrunner/tlp
sudo apt-get update
sudo apt-get install tlp tlp-rdw
sudo tlp start

# Install undistract-me for terminal notifications when long running tasks complete
sudo apt-get install  undistract-me
sed -i '$ a\\n. /usr/share/undistract-me/long-running.bash' ~/.bashrc
sed -i '$ a\notify_when_long_running_commands_finish_install' ~/.bashrc

# Install preload to speed-up application load time
sudo apt-get install preload

# Suppress language related updates from apt-get
sudo sed -i '$ a\Acquire::Languages "none";' /etc/apt/apt.conf.d/00aptitude

# Remove default installed games
sudo apt-get remove gnome-mines aisleriot gnome-mahjongg gnome-sudoku

# Install Atom text editor
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom

# Install openssh-server to enable incomming ssh connections
sudo apt-get install openssh-server
sudo sed -i '$ a\AllowUsers '$USER /etc/ssh/sshd_config

# Install chromium open-source browser
sudo apt-get install chromium-browser

# Change wallpaper to salcantayperu
gsettings set org.gnome.desktop.background picture-uri file:/usr/share/backgrounds/salcantayperu_by_Life_Nomadic.jpg

# Disable bluetooth on startup
sudo sed -i '$ i\rfkill block bluetooth\n' /etc/rc.local

# Install PyCharm CE
sudo add-apt-repository "deb http://archive.getdeb.net/ubuntu $(lsb_release -sc)-getdeb apps"
wget -q -O- http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install pycharm
